sig-net/mpc

.cargo/config.toml

**NOTE**: requires at least Xcode 15 to be installed on your mac machine.
Goes from 11m to 5m fresh integration test build with this.

feat: added faster linker for macos

---

chain-signatures/node/src/protocol/message.rs
chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/triple.rs
chain-signatures/node/src/storage/error.rs
chain-signatures/node/src/storage/triple_storage.rs
integration-tests/chain-signatures/tests/cases/mod.rs

Making all operations atomic prevents race conditions, especially in multithreaded and multi-node design. It also decreases the number of Redis calls and simplifies the code, although we lose some error types.
I plan to adopt this approach in other places if we stick with it.

Take two triples in atomic way

---

chain-signatures/node/src/mesh/connection.rs
chain-signatures/node/src/mesh/mod.rs

Using tokio JoinSet.
`pub async fn ping(self: Arc<Self>) -> Participants` takes in Arc<Self> so that it can be passed among different tasks when calling `join_set.spawn()`

fetch participant state parallel

---

chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/storage/error.rs
chain-signatures/node/src/storage/presignature_storage.rs
chain-signatures/node/src/storage/triple_storage.rs

Insert and take operations must be atomic. Lua may seem an overhead when we have 2 simple operations, but I want to have a unified approach for storage and flexibility. Already planning to extend those scripts with additional checks.
Also, scripts can be preloaded to Redis, so there is no need to transfer and build them on each call. We may add that optimization when required.

Atomic insertion of presignatures and triples

---

chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/signature.rs
chain-signatures/node/src/protocol/triple.rs
chain-signatures/node/src/storage/presignature_storage.rs
chain-signatures/node/src/storage/triple_storage.rs
integration-tests/tests/cases/mod.rs

We are having issues with the pre-signature usage. We should be 100% sure that is never the case. The same goes for triples.
In this PR, I've made the system strict. We should not allow the reinsertion of used triples and pre-signatures.
I've removed the reinsertion logic, it is seldom, but adds complexity to the logic.
Should fix https://github.com/sig-net/mpc/issues/40

Restrict triples and presignatures reusage

---

.github/workflows/integration.yml
.github/workflows/nightly.yml
chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/signature.rs
chain-signatures/node/src/protocol/triple.rs
chain-signatures/node/src/storage/presignature_storage.rs
chain-signatures/node/src/storage/triple_storage.rs
integration-tests/README.md
integration-tests/src/containers.rs
integration-tests/tests/cases/mod.rs

- Adds back triple and presignatures to storage if they do not meet the threshold criteria. A new parameter `back` is added for cases where we are sure we want to add these back to storage. Mainly added back to circumvent the cases of inconsistency when one node decides to drop a triple and presignature but others do not or were not aware of it. In the current code, they would never drop these as they do not own them and will purely sit in storage. It's better to have the chance later to use them otherwise we'd still be at the same problem of taking up maximum amount of triples/presignatures we can have per the config.
- Updates to redis 7.4.2 in tests for `HEXPIRE` where `EXPIRE` was deleting the whole set before, which isn't ideal for when we want to expire per triple id or presignature …

fix: added triples and presigs back to storage and fix EXPIRE on used

---

chain-signatures/node/src/indexer.rs

make sure we get the specific error for why lake was not able to be build within indexer

fix: report error on lake build failure

---

.cargo/config.toml

No longer need these requirements because once we update macos xcode to 15 or later, these should be enabled by default

chore: remove linker requirements for macos

---

chain-signatures/node/src/cli.rs
chain-signatures/node/src/indexer_eth.rs
chain-signatures/node/src/metrics.rs
integration-tests/src/containers.rs
integration-tests/src/lib.rs
integration-tests/src/local.rs
integration-tests/src/main.rs

- this will enable the eth indexer to start from block_number = latest_block from rpc call - 15 if the last_processed_block was empty or too far behind.
- Also added 2 metrics: eth sign request count and eth indexed block height

Eth indexer not require start block env variable

---

chain-signatures/Cargo.lock
chain-signatures/node/Cargo.toml
integration-tests/Cargo.lock
integration-tests/Cargo.toml

This sets `cait-sith` dependency to our own repo's cait-sith for future changes and audit fixes

chore: set cait-sith to our own repo & fix related audit issues

---

chain-signatures/node/src/cli.rs
chain-signatures/node/src/lib.rs
chain-signatures/node/src/logs.rs
integration-tests/src/containers.rs
integration-tests/src/lib.rs
integration-tests/src/local.rs

Makes debugging what is going wrong with a specific node by introducing the `NodeId(id)` appended to every logline in integration tests. These will not appear on the actual prod environments.
For example:
```sh
NodeId(1) 2025-01-17T21:54:40.653693Z  INFO mpc_node::protocol::consensus: started(initializing): starting key generation as a part of the participant set
```

feat: add NodeId(id) to every log entry for integration-tests

---

chain-signatures/contract-eth/README.md
chain-signatures/contract-eth/hardhat.config.js
chain-signatures/contract-eth/ignition/params.json
chain-signatures/node/src/cli.rs
chain-signatures/node/src/indexer_eth.rs
chain-signatures/node/src/metrics.rs
chain-signatures/node/src/protocol/mod.rs
chain-signatures/node/src/web/mod.rs
integration-tests/src/containers.rs
integration-tests/src/lib.rs
integration-tests/src/local.rs
integration-tests/src/main.rs

This PR changes the way we get sign requests from ethereum chain. Previously, we pull for latest block every 5 seconds, if there is a request in the block, we process it. The problem with that is that there's always a delay between block becoming available and us pulling for it no matter how frequent we pull.
The approach in this PR is, we subscribe to the logs in the sign request via web socket, and those logs will be pushed to us when they become available. This will minimize delay in previous approach.
There is much less ethereum RPC calls to be made because we essentially have one web socket and that's it.

eth indexer: subscribe to log events instead of pulling blocks

---

chain-signatures/contract/src/config/impls.rs
chain-signatures/contract/src/lib.rs
chain-signatures/contract/tests/user_views.rs
chain-signatures/node/src/protocol/presignature.rs
integration-tests/src/lib.rs

Let's set the default number of concurrent protocols to a higher number. This should stress test our multithreading design and messaging layer.
At first, I wanted to separate the T and P parameters, but this made little sense while introducing the breaking change.
The number of signature protocols remains unconstrained. Limits for T and P protocols are separate (each node can introduce 512 T and 512 P protocols and as a result process 1024*12(number of nodes in the system) parallel protocols)
cc @auto-mausx 
@ChaoticTempest ~12,000 Tokyo tasks seem reasonable since they are mostly IO-bound. We can adjust these numbers after we have more metrics. For now higher number will give us better data.

Update protocol default configs

---

chain-signatures/node/src/metrics.rs
chain-signatures/node/src/protocol/signature.rs
chain-signatures/node/src/rpc.rs

Add additional metrics for signing:
- signature generation latency: time taken between request received and signature generation completed.
- respond latency: time it takes to publish the signature. 
- logging now has the elapsed times as well for signatures.
We can see how long signature generation takes a bit more precisely with this

chore: add separate metrics for sign respond and sign generation

---

API.md

The correct spelling of the function is `experimental_signature_deposit`. The code has it spelled correctly. But in the docs it was `experimantal_signature_deposit`.
Also, the link to the source code used the wrong path, with the directory name `chain-signatures/contracts` instead of `chain-signatures/contract`.

doc: fix typos in API docs

---

integration-tests/src/cluster/mod.rs
integration-tests/src/cluster/spawner.rs
integration-tests/src/lib.rs
integration-tests/src/main.rs
integration-tests/src/utils.rs

was getting annoyed by all the misc integration keys appearing in the `integration-tests` folder. So now they'll be populated under `target/tmp` folder.
Also made a few things parameterizable like GCP project id and env if that matters for anybody.

chore: added tmp_dir for proper key cleanup

---

.dockerignore
.github/workflows/deploy-dev-contract.yml
.github/workflows/deploy-dev-nodes.yml
.github/workflows/unit.yml
Dockerfile

hopefully this fixes:
```sh
buildx failed with: ERROR: failed to solve: process "/bin/sh -c cargo build --release --package mpc-node" did not complete successfully: exit code: 101
```
Still not sure why it's failing even though building the image locally succeeds (on both macos and ubuntu). So I pretty much just included everything within the cargo workspace to see if that's the issues

fix: docker build 

---

Dockerfile

this fixes the docker build because the artifacts were not copied to the right folder

fix: docker path

---

chain-signatures/node/src/protocol/cryptography.rs
chain-signatures/node/src/protocol/message.rs

Nodes don't necessarily hop online instantly for generation, that means they can restart or be in offline state when generation has just occurred. In this case, an active node may send a message way too earlier, leading it to be binned or missed by nodes that have not started yet. They would never receive these messages due to the retrying mechanism for this being inside the message channel.
We need to try and send it to all participants instead, and let the message channel retry where possible.

fix: generation should be on all participants not active

---

chain-signatures/contract-eth/contracts/ChainSignatures.sol
chain-signatures/contract-eth/test/ChainSignatures.test.js

error (Special Solidity Feature)
Introduced in Solidity 0.8.4.
Allows defining custom errors that can be used with revert, making reverts more gas-efficient compared to require with string messages.
Example:
```
error Unauthorized(address user);
function restrictedFunction() public {
if (msg.sender != owner) {
revert Unauthorized(msg.sender);
}
}
```
Using error is cheaper than reverting with a string message because it avoids storing large strings in transaction logs.
We should not use `error` as variable name

eth contract: replace error with other var names

---

chain-signatures/node/src/protocol/message.rs
chain-signatures/node/src/protocol/signature.rs

discovered that eth requests fail when it did not succeed on 1st generator, and need to retry.
Poking the logs, I find that the non-proposer nodes were warning `waiting for indexer`. This means that the request has been removed from sign_queue, and not added back.
This should affect near requests as well, but likely near block time is fast thus less delay on indexer side, thus most requests finish in first attempt.

fix: push failed signature request into sign queue for non-proposers

---

chain-signatures/contract-eth/contracts/ChainSignatures.sol

Auditors:
```
Using transfer may fail on chains with higher gas costs (e.g., zkSync Era). Since only the admin withdraws fees, switching to a call is recommended.
```

Use low level `call` func to withdraw

---

chain-signatures/node/src/protocol/mod.rs

The version is parsed correctly, no harm in having some tests on top.
On dev I've executed curl inside of K8s and got correct version
```
multichain_node_version{node_account_id="multichain-node-dev-0.testnet"} 1001000000
```
The issue lies somewhere else

test version node

---

chain-signatures/node/src/indexer.rs

do not block main runtime thread while in the runtime itself for indexer

fix: use backoff async for runtime sleep in indexer

---

.cargo/config.toml
integration-tests/.cargo/config.toml
setup.sh

Looks like adding the runner to a package specific config.toml doesn't work very well, so moving it back to root dir. This also fixes the `setup.sh` for zsh related environments since that env passes down script args from parent to child automatically

fix: build script for zsh and fix cargo/.config.toml

---

chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/triple.rs

Sometimes, there will be an issue with taking foreign owned triples: `presignature cannot be generated id=12317391677896674303 err=TripleStoreError("failed to take two triples Redis(Triple: 8442524960860672804 cannot be taken as foreign)`. This is because the `triple_is_mine` selection had an issue where the passed in `participant` list for `TripleGenerator` was out of order. To remedy this, we have to sort the participant list at the beginning of the `TripleGenerator`.

fix: taking foreign triple bug

---

chain-signatures/node/src/indexer.rs
chain-signatures/node/src/indexer_eth.rs
chain-signatures/node/src/metrics.rs
chain-signatures/node/src/protocol/mod.rs
chain-signatures/node/src/protocol/signature.rs
chain-signatures/node/src/rpc.rs

We observed that some nodes will stop receiving eth requests after running for a while.
I investigated online for a bit, seems like it's related to infura dropping the websocket while we are subscribed: https://github.com/INFURA/infura/issues/117
This PR basically unscuscribe and resubscribe when there has been no sign events in the past 60s. Choosing this solution because Infura has not committed to emitting any events to indicate they have dropped our connection. 
I tried requesting block number using websocket to keep the subscription alive as suggested by one comment in the infura issue, but while the web socket is alive and block number call keeps succeeding, subscription still won't receive new events. So I changed to unsubscribe and resubscribing. 
Also added catchup logic whenever …

fix: resubscribe to eth logs if no eth events in 60s

---

chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/signature.rs

- fixes infinitely looping over sign requests when retrying.
- trash presignatures and triples that do not meet threshold requirements for now until we implement github.com/sig-net/mpc/issues/130

hotfix: do not infinitely loop signature request & do trash presignature/triples 

---

chain-signatures/node/src/protocol/message/mod.rs
chain-signatures/node/src/protocol/signature.rs

We need to have this info so that we identify correctly which specific sign request is erroring out in logs

chore: add sign_id/presignature_id to erroring out signatures

---

chain-signatures/node/src/mesh/connection.rs
chain-signatures/node/src/protocol/message/filter.rs
chain-signatures/node/src/protocol/sync/mod.rs

Remove custom tracing targets for now, since they aren't showing at all in our GCP logs.

fix: gcp logs not showing custom target

---

chain-signatures/node/src/protocol/sync/mod.rs

For large enough storage sizes, the fetching of keys and intersection can take a bit of time. So bump this to 500ms for now and I'll add more strict benchmarks for this later

fix: bump timeout of sync requests to 500ms

---

chain-signatures/node/src/protocol/sync/mod.rs
integration-tests/tests/cases/sync.rs

This fixes the timeouts on dev since devnet has a large stockpile of triples/presignatures. Loading their IDs in every 250ms isn't the best idea, especially since we load one for every participant since each participant will ping us. Each call to load foreign IDs for around ~3000 triples takes about 20ms.
To fix this, this PR moves the processing of `SyncUpdate` into a separate task and now only gets a view of triple and presignature IDs every 500ms.

fix: sync timeout due to large amounts of triples & presignatures being loaded

---

chain-signatures/node/src/metrics.rs
chain-signatures/node/src/protocol/triple.rs

Problems:
1. triple before poke delay showing constant value all the time
2. triple accrued delay p95 is too low (<10ms)
Changes:
1. modify the buckets for the triple metrics
This is important because these metrics are histogram metrics, and the values in the bucket is used as the upper bound of each value interval. And the metric counts how many observed values fall in each interval.
Previously the triple before poke delay metric's bucket has the largest upper bound set too low, which explains why the metric shows a constant value for p20, p50, p95, because the observed values are mostly greater than the biggest upper bound.
3. Lock the poked_latest field of triple generator.
This is necessary because in the current code, the triple generator can be poked by multiple tasks at the same …

performance metrics: fix triple metrics

---

chain-signatures/node/src/metrics.rs

Problem:
Still most triple accrued wait is greater than the current ceiling value
I checked that the number of waits observed looks correct, so it's the buckets still lacking bigger buckets. 
Solution:
Up the accrued wait ceiling by a lot.

perf metrics: increase the upper range for accrued delay and triple pokes

---

chain-signatures/node/src/indexer.rs
chain-signatures/node/src/mesh/connection.rs
chain-signatures/node/src/mesh/mod.rs
chain-signatures/node/src/web/mod.rs

`is_stable` has been set to a constant of `true` since #241
The `is_stable` flag was useful when we only looked at the near indexer. It checked of the indexer data is behind.
But now with many chains integrated, we want to move away from chain-specific checks. Hence, is_stable should go away entirely.
This PR removes dead code that was still around from the old is_stable check and  renames some field to make it easier to understand what actually happens.
Specifically, replace `NodeStatus::Active(IsStable=true)` with `NodeStatus::Active`.
For the case where the peer node is online but it still is in a protocol state where it is not ready to participate, we now use `NodeStatus::Inactive`. (Before, we used `NodeStatus::Active(IsStable=false)` for that, although it doesn't really have …

refactor: delete unused `is_stable` code

---

chain-signatures/node/src/protocol/sync/mod.rs
chain-signatures/node/src/storage/presignature_storage.rs
chain-signatures/node/src/storage/triple_storage.rs
chain-signatures/node/src/web/mod.rs
integration-tests/src/cluster/mod.rs
integration-tests/src/cluster/spawner.rs
integration-tests/src/lib.rs
integration-tests/tests/cases/mod.rs
integration-tests/tests/cases/sync.rs

This makes the `/sync` endpoint return json. This is because `post_json` expects a return value in Json. This was fixed in the other PR in https://github.com/sig-net/mpc/pull/313 but just going to pull it out and put it here just so we can push it in.
This also adds in two integration test, a basic sync test and a full e2e check on syncing.

fix: make /sync return json & add more integration tests

---

chain-signatures/node/src/cli.rs
chain-signatures/node/src/protocol/consensus.rs
chain-signatures/node/src/protocol/cryptography.rs
chain-signatures/node/src/protocol/mod.rs
chain-signatures/node/src/protocol/signature.rs

This removes the `ConsensusCtx` and `CryptographicCtx` traits and `Ctx` struct since they don't add much value. Instead, we will use `MpcSignProtocol` struct directly. This cuts down the boilerplate and anytime we want to add in new fields, we would have to modify those traits.
This also removes `async_trait` since rust 1.75 stabilized async fn in traits. The only caveat is that these traits can no longer be `pub`lic, but `pub(crate)` due to bounds limitations. We don't really care about that case since we're not writing a public facing library with the `mpc-node` crate anyways.

chore: remove ctx traits

---

chain-signatures/node/src/indexer_sol.rs
chain-signatures/node/src/rpc.rs
integration-tests/src/lib.rs

Separating solana websocket and http rpc url so that we could use alchemy http url for respond() calls and would be able to respond when traffic is high

separate solana websocket and http rpc url to use alchemy for http respond()

---

chain-signatures/node/src/logs.rs
integration-tests/src/lib.rs

this didn't get explicitly disabled for integration tests before

fix: make integration tests disable gcp logging

---

chain-signatures/node/src/protocol/consensus.rs
chain-signatures/node/src/protocol/cryptography.rs
chain-signatures/node/src/protocol/mod.rs
chain-signatures/node/src/protocol/state.rs
chain-signatures/node/src/rpc.rs

This is a smaller PR in the grander scheme of making our state machine more versatile. We originally had the premise that on any error, we should revert the state back to the previous state. This however created a couple of unforeseen issues along the way such as going into weird states we shouldn't be going to.
This is the start of making our state machine more explicit in the fact that we should only be transitioning into states we want to transition into. No panics and errors are to be returned, instead if we truly cannot recover, we should go into a FailedState where recovery is only feasible if we certain conditions are met and if not, we can either wait for network input or shutdown the node.
The changes in this PR are as follows:
- `CryptographicProtocol` no longer returns an …

feat: make CryptographicProtocol not return err

---

chain-signatures/node/src/indexer_eth.rs

the block hash for the finalized block was wrongly set to its parent hash. Correcting it.

bug: correct the block hash for eth finalized block

---

chain-signatures/node/src/cli.rs
chain-signatures/node/src/protocol/consensus.rs
chain-signatures/node/src/protocol/cryptography.rs
chain-signatures/node/src/protocol/message/mod.rs
chain-signatures/node/src/protocol/mod.rs
chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/state.rs
chain-signatures/node/src/protocol/sync/mod.rs
chain-signatures/node/src/rpc.rs
chain-signatures/node/src/storage/secret_storage.rs
chain-signatures/node/src/types.rs
chain-signatures/node/src/web/error.rs
chain-signatures/node/src/web/mod.rs
integration-tests/benches/store.rs
integration-tests/tests/cases/sync.rs

This continues the work started in https://github.com/sig-net/mpc/pull/374. This will make it so that we no longer do a clone on our node/protocol state when we try to make a state advancement. This means that any state machine changes that could fail or error out in some manner will need to be done explicitly and not through reversions.
We actually had a good state to transition to already when we go into a failed state. It's the `Joining` state since most of the errors are just mismatched configurations between contract and our node, it just means that the contract is ahead or behind node. If its ahead, then that means a resharing step has already completed and so we just need to rejoin.
Note `NodeStateWatcher` was renamed to `ContractStateWatcher`, since a new `NodeStateWatcher` struct …

feat: consensus no longer return error & no more cloning on protocol state changes

---

chain-signatures/node/src/protocol/consensus.rs
chain-signatures/node/src/protocol/cryptography.rs
chain-signatures/node/src/protocol/message/mod.rs
chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/state.rs
chain-signatures/node/src/protocol/triple.rs
chain-signatures/node/src/util.rs
integration-tests/tests/cases/store.rs

This makes it so that presignature generation is done through a separate task similar to https://github.com/sig-net/mpc/pull/388 with triples. One extra thing that had to be done with this PR was that the new presignature task will have to check by itself whether the triples are available or not in storage. If they're the owner, they already have the triples, but if they're not, then they will need to fetch and wait until its available in storage.

feat: presignature as individual tasks

---

.github/workflows/k6-ci-loadtest.yml

This should allow the continual load tests to run on Solana dev on our self hosted runners. I kept the original CI test, but we can update that if needed later.

FEAT: Added GHA job to run on a schedule

---

.github/workflows/unit.yml
Cargo.lock
chain-signatures/node/Cargo.toml

RUSTSEC-2024-0437 solved by bumping prometheus from 0.13.4 to 0.14.0
changelog: https://github.com/tikv/rust-prometheus/blob/master/CHANGELOG.md#0140
We need to ignore some checks temporarily to make the `cargo audit` check meaningful again. Otherwise, we don't even notice when we are affected by new CVEs.
RUSTSEC-2024-0421 -> see #414
RUSTSEC-2025-0009 -> see #415
RUSTSEC-2024-0336 -> see #415

fix CI cargo audit checks

---

chain-signatures/node/src/protocol/posit.rs
chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/signature.rs
chain-signatures/node/src/protocol/triple.rs
integration-tests/src/cluster/mod.rs
integration-tests/src/cluster/spawner.rs
integration-tests/src/containers.rs
integration-tests/src/lib.rs
integration-tests/src/local.rs
integration-tests/tests/cases/mod.rs
integration-tests/tests/cases/sync.rs

Currently, since posits are checking whether or not a sign_id is ongoing or not, it is likely that there's race conditions between two different attempts for the same sign request. For example, a sign request can be ongoing but then fail for some reason. Some nodes will still have it as ongoing, but others will have moved on and tried to restart it. Best to just maintain two separate sign request attempts at this point (such as a mapping of (SignId, PresignatureId) to SignAttempt).
This also adds in a check for checking the proposer is correct or not on the sign request, since sign request has this knowledge early on based on organization. Before, we were reorganizing requests on every potential failure, but since we added posits, things are a bit different now. So we have to send it back …

fix: signature ongoing collisions

---

chain-signatures/node/src/indexer.rs
chain-signatures/node/src/indexer_eth.rs
chain-signatures/node/src/indexer_sol.rs
chain-signatures/node/src/protocol/signature.rs
integration-tests/src/main.rs

1. add a field total_timeout to IndexedSignRequest
2. configure different chains to have a different total timeout 
3. expire requests in sign queue according to this total timeout

fix: expire eth and solana requests with different timeouts

---

.github/workflows/integration.yml
.github/workflows/unit.yml

Since now we require tests to pass before merging, we need to run the workflow on all PRs.
We will not do that on each commit, but it must happen at least once per PR.

Run the PR workflow on any file change

---

chain-signatures/node/src/protocol/message/mod.rs
chain-signatures/node/src/protocol/posit.rs
chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/signature.rs
chain-signatures/node/src/protocol/triple.rs

Testing this to see how much better our messaging is. In the future, sending messages out should be a bit smarter and more reactive by reaching the payload limit or timeout.
With this, I've noticed a slight performance increase in our `test_signature_basic` test by about 5-10s

feat: lower message loop sleep interval

---

chain-signatures/contract-eth/scripts/requestSign.js
chain-signatures/node/src/indexer_eth.rs

Changes involved:
1. the finalized_block_channel only save the latest finalized block number
2. in send_requests_when_final, once the request's block number <= finalized block number, and its block hash == block hash from helios, we send the request to sign queue

eth indexer: use helios to directly query for finalized blocks

---

chain-signatures/node/src/cli.rs
chain-signatures/node/src/config.rs
chain-signatures/node/src/metrics.rs
chain-signatures/node/src/node_client.rs
chain-signatures/node/src/protocol/cryptography.rs
chain-signatures/node/src/protocol/message/filter.rs
chain-signatures/node/src/protocol/message/mod.rs
chain-signatures/node/src/protocol/message/sub.rs
chain-signatures/node/src/protocol/mod.rs
chain-signatures/node/src/rpc.rs
chain-signatures/node/src/web/error.rs
chain-signatures/node/src/web/mod.rs
integration-tests/tests/cases/store.rs

This change makes it so that the message inbox and outbox are completely async. Triples, Presignatures, and Signature when subscribing for messages stays the same. Generating and Resharing states now get their messages within their `Action::Wait` step, where there's a global subscriber/receiver for generating and resharing messages in the `MpcSignProtocol`. When we make generating and resharing more async (as in their own task), then we can move these subscribers there. Until then, they'll stay in the global context of the node.
- No more `MessageReceiver` interface.
- No more `MessageExecutor` (replaced by `MessageInbox` and `MessageOutbox` individual tasks).
- PROTOCOL_LATENCY_ITER_MESSAGE is no longer used since message is now no longer a part of state machine.
- MESSAGE_QUEUE_SIZE was …

feat: make MessageInbox/Outbox fully async

---

chain-signatures/node/src/indexer_eth.rs
chain-signatures/node/src/rpc.rs

We still want to run catchup first because otherwise the last processed block will be confusing.
in this pr, we send catchup blocks and the blocks from block_heads_rx to a channel to make sure they come in order. And the main loop will consume blocks to process from this channel.

eth indexer: run catchup first so last processed block is accurate

---

chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/triple.rs

This should fix the issue with no mine presignatures. This is because when we abort a protocol, the `introduced` counter never gets resetted and so we end up with no presignatures being generated by that particular node if they've failed enough over time.

fix: stockpiling not working due introduction

---

chain-signatures/node/src/protocol/posit.rs
chain-signatures/node/src/protocol/presignature.rs
chain-signatures/node/src/protocol/signature.rs
chain-signatures/node/src/protocol/triple.rs

This is most likely what was causing our introduction issue. We should timeout not at the beginning of the protocol loop, but when trying to receive messages. This is because when awaiting for a message, it will stall till the next message, meaning we don't check the timeout until we get a new message if ever. This means that there will be a set of owned ongoing generators that will never wake up given that they receive no messages, which means our introduced "counter" never gets decremented since there will be live generators that never expire that contribute to this count.

fix: wait should timeout instead of checking at beginning of protocol

---

chain-signatures/node/src/cli.rs
chain-signatures/node/src/protocol/mod.rs
chain-signatures/node/src/protocol/signature.rs

This adds the signature proposer election based on rounds by @jakmeier previously with https://github.com/sig-net/mpc/pull/410.
This is a bit different since the rounds are stored in the `SignRequest` struct. So the newly organized request will start from there on reorganization of proposer.

feat: added signature proposer election by rounds

---

chain-signatures/node/src/protocol/message/mod.rs
chain-signatures/node/src/storage/secret_storage.rs
integration-tests/src/mpc_fixture/builder.rs
integration-tests/src/mpc_fixture/fixture_tasks.rs
integration-tests/tests/cases/mpc.rs

Adds a test that would fail without the fix in #485

add regression test for presignature timeout

---

chain-signatures/node/src/protocol/message/mod.rs
integration-tests/tests/cases/mpc.rs

Retrying messages may be a little bit aggressive, so let's bump it to 500ms

fix: make retrying messages less aggressive
